# Generated by Django 5.2.2 on 2025-06-05 08:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('projects_created', models.IntegerField(default=0, verbose_name='Создано проектов')),
                ('tasks_created', models.IntegerField(default=0, verbose_name='Создано задач')),
                ('tasks_completed', models.IntegerField(default=0, verbose_name='Завершено задач')),
                ('active_users', models.IntegerField(default=0, verbose_name='Активных пользователей')),
            ],
            options={
                'verbose_name': 'Статистика',
                'verbose_name_plural': 'Статистика',
                'ordering': ['-date'],
            },
        ),
    ]
